# Generated by Django 4.0.7 on 2022-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
